python save_resnet18_test_scores.py --arch 'resnet18' --dataseparate '10-90' --lr 0.0006 --start-epoch 29 --epochs 30 --datasettype='test' --has_weights='False' --distill 'True' --dataroot '/home/h/Downloads/plantvillage_deeplearning_paper_dataset' --saveroot '/media/h/resnet18' &&\
    python save_resnet18_test_scores.py --arch 'resnet18' --dataseparate '20-80' --lr 0.0006 --start-epoch 29 --epochs 30 --datasettype='test' --has_weights='False' --distill 'True' --dataroot '/home/h/Downloads/plantvillage_deeplearning_paper_dataset' --saveroot '/media/h/resnet18' &&\
    python save_resnet18_test_scores.py --arch 'resnet18' --dataseparate '40-60' --lr 0.0006 --start-epoch 29 --epochs 30 --datasettype='test' --has_weights='False' --distill 'True' --dataroot '/home/h/Downloads/plantvillage_deeplearning_paper_dataset' --saveroot '/media/h/resnet18' &&\
    python save_resnet18_test_scores.py --arch 'resnet18' --dataseparate '50-50' --lr 0.0006 --start-epoch 29 --epochs 30 --datasettype='test' --has_weights='False' --distill 'True' --dataroot '/home/h/Downloads/plantvillage_deeplearning_paper_dataset' --saveroot '/media/h/resnet18' &&\
    python save_resnet18_test_scores.py --arch 'resnet18' --dataseparate '60-40' --lr 0.0006 --start-epoch 29 --epochs 30 --datasettype='test' --has_weights='False' --distill 'True' --dataroot '/home/h/Downloads/plantvillage_deeplearning_paper_dataset' --saveroot '/media/h/resnet18' &&\
    python save_resnet18_test_scores.py --arch 'resnet18' --dataseparate '80-20' --lr 0.0006 --start-epoch 29 --epochs 30 --datasettype='test' --has_weights='False' --distill 'True' --dataroot '/home/h/Downloads/plantvillage_deeplearning_paper_dataset' --saveroot '/media/h/resnet18' &&\
    python save_resnet18_test_scores.py --arch 'resnet18' --dataseparate '10-90' --lr 0.0006 --start-epoch 29 --epochs 30 --datasettype='test' --has_weights='False' --distill 'MSETrue' --dataroot '/home/h/Downloads/plantvillage_deeplearning_paper_dataset' --saveroot '/media/h/resnet18' &&\
    python save_resnet18_test_scores.py --arch 'resnet18' --dataseparate '20-80' --lr 0.0006 --start-epoch 29 --epochs 30 --datasettype='test' --has_weights='False' --distill 'MSETrue' --dataroot '/home/h/Downloads/plantvillage_deeplearning_paper_dataset' --saveroot '/media/h/resnet18' &&\
    python save_resnet18_test_scores.py --arch 'resnet18' --dataseparate '40-60' --lr 0.0006 --start-epoch 29 --epochs 30 --datasettype='test' --has_weights='False' --distill 'MSETrue' --dataroot '/home/h/Downloads/plantvillage_deeplearning_paper_dataset' --saveroot '/media/h/resnet18' &&\
    python save_resnet18_test_scores.py --arch 'resnet18' --dataseparate '50-50' --lr 0.0006 --start-epoch 29 --epochs 30 --datasettype='test' --has_weights='False' --distill 'MSETrue' --dataroot '/home/h/Downloads/plantvillage_deeplearning_paper_dataset' --saveroot '/media/h/resnet18' &&\
    python save_resnet18_test_scores.py --arch 'resnet18' --dataseparate '60-40' --lr 0.0006 --start-epoch 29 --epochs 30 --datasettype='test' --has_weights='False' --distill 'MSETrue' --dataroot '/home/h/Downloads/plantvillage_deeplearning_paper_dataset' --saveroot '/media/h/resnet18' &&\
    python save_resnet18_test_scores.py --arch 'resnet18' --dataseparate '80-20' --lr 0.0006 --start-epoch 29 --epochs 30 --datasettype='test' --has_weights='False' --distill 'MSETrue' --dataroot '/home/h/Downloads/plantvillage_deeplearning_paper_dataset' --saveroot '/media/h/resnet18'
