python save_resnet18_test_scores.py --arch 'resnet101' --dataseparate '10-90' --datasettype='train' --has_weights='True' --dataroot '/home/h/Downloads/plantvillage_deeplearning_paper_dataset' --saveroot '/media/h/resnet101' && \
python save_resnet18_test_scores.py --arch 'resnet101' --dataseparate '20-80' --datasettype='train' --has_weights='True' --dataroot '/home/h/Downloads/plantvillage_deeplearning_paper_dataset' --saveroot '/media/h/resnet101' && \
python save_resnet18_test_scores.py --arch 'resnet101' --dataseparate '40-60' --datasettype='train' --has_weights='True' --dataroot '/home/h/Downloads/plantvillage_deeplearning_paper_dataset' --saveroot '/media/h/resnet101'  && \
python save_resnet18_test_scores.py --arch 'resnet101' --dataseparate '50-50' --datasettype='train' --has_weights='True' --dataroot '/home/h/Downloads/plantvillage_deeplearning_paper_dataset' --saveroot '/media/h/resnet101'  && \
python save_resnet18_test_scores.py --arch 'resnet101' --dataseparate '60-40' --datasettype='train' --has_weights='True' --dataroot '/home/h/Downloads/plantvillage_deeplearning_paper_dataset' --saveroot '/media/h/resnet101'  && \
python save_resnet18_test_scores.py --arch 'resnet101' --dataseparate '80-20' --datasettype='train' --has_weights='True' --dataroot '/home/h/Downloads/plantvillage_deeplearning_paper_dataset' --saveroot '/media/h/resnet101'  && \
python save_resnet18_test_scores.py --arch 'resnet101' --dataseparate '10-90' --datasettype='train' --has_weights='False' --dataroot '/home/h/Downloads/plantvillage_deeplearning_paper_dataset' --saveroot '/media/h/resnet101' && \
python save_resnet18_test_scores.py --arch 'resnet101' --dataseparate '20-80' --datasettype='train' --has_weights='False' --dataroot '/home/h/Downloads/plantvillage_deeplearning_paper_dataset' --saveroot '/media/h/resnet101'  && \
python save_resnet18_test_scores.py --arch 'resnet101' --dataseparate '40-60' --datasettype='train' --has_weights='False' --dataroot '/home/h/Downloads/plantvillage_deeplearning_paper_dataset' --saveroot '/media/h/resnet101'  && \
python save_resnet18_test_scores.py --arch 'resnet101' --dataseparate '50-50' --datasettype='train' --has_weights='False' --dataroot '/home/h/Downloads/plantvillage_deeplearning_paper_dataset' --saveroot '/media/h/resnet101'  && \
python save_resnet18_test_scores.py --arch 'resnet101' --dataseparate '60-40' --datasettype='train' --has_weights='False' --dataroot '/home/h/Downloads/plantvillage_deeplearning_paper_dataset' --saveroot '/media/h/resnet101'  && \
python save_resnet18_test_scores.py --arch 'resnet101' --dataseparate '80-20' --datasettype='train' --has_weights='False' --dataroot '/home/h/Downloads/plantvillage_deeplearning_paper_dataset' --saveroot '/media/h/resnet101'  && \
python save_resnet18_test_scores.py --arch 'resnet101' --dataseparate '10-90' --datasettype='train' --has_weights='False' --dataroot '/home/h/Downloads/plantvillage_deeplearning_paper_dataset' --saveroot '/media/h/resnet101'  --softlogits='True' && \
python save_resnet18_test_scores.py --arch 'resnet101' --dataseparate '20-80' --datasettype='train' --has_weights='False' --dataroot '/home/h/Downloads/plantvillage_deeplearning_paper_dataset' --saveroot '/media/h/resnet101'  --softlogits='True'  && \
python save_resnet18_test_scores.py --arch 'resnet101' --dataseparate '40-60' --datasettype='train' --has_weights='False' --dataroot '/home/h/Downloads/plantvillage_deeplearning_paper_dataset' --saveroot '/media/h/resnet101'  --softlogits='True'  && \
python save_resnet18_test_scores.py --arch 'resnet101' --dataseparate '50-50' --datasettype='train' --has_weights='False' --dataroot '/home/h/Downloads/plantvillage_deeplearning_paper_dataset' --saveroot '/media/h/resnet101'  --softlogits='True'  && \
python save_resnet18_test_scores.py --arch 'resnet101' --dataseparate '60-40' --datasettype='train' --has_weights='False' --dataroot '/home/h/Downloads/plantvillage_deeplearning_paper_dataset' --saveroot '/media/h/resnet101'  --softlogits='True'  && \
python save_resnet18_test_scores.py --arch 'resnet101' --dataseparate '80-20' --datasettype='train' --has_weights='False' --dataroot '/home/h/Downloads/plantvillage_deeplearning_paper_dataset' --saveroot '/media/h/resnet101'  --softlogits='True'
